import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy - The Joy Junction",
  description: "Read the Privacy Policy for The Joy Junction.",
};

export default function PrivacyPolicyPage() {
  const lastUpdated = "June 8, 2025"; // Update this date as needed

  return (
    <div className="bg-slate-100 min-h-screen py-12 sm:py-16 lg:py-20">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        <header className="mb-10 text-center">
          <h1 className="text-4xl font-extrabold text-slate-900 sm:text-5xl">
            Privacy Policy
          </h1>
          <p className="mt-4 text-md text-slate-600">
            Last Updated: {lastUpdated}
          </p>
        </header>

        <article className="prose prose-slate lg:prose-lg max-w-none">
          <h2>1. Interpretation and Definitions</h2>

          <h3>Interpretation</h3>
          <p>
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear in
            singular or in plural.
          </p>

          <h3>Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul>
            <li>
              <strong>Account</strong> means a unique account created for You to
              access our Service or parts of our Service.
            </li>
            <li>
              <strong>Affiliate</strong> means an entity that controls, is
              controlled by or is under common control with a party, where
              &quot;control&quot; means ownership of 50% or more of the shares,
              equity interest or other securities entitled to vote for election
              of directors or other managing authority.
            </li>
            <li>
              <strong>Company</strong> (referred to as either &quot;the
              Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot;
              in this Agreement) refers to The Joy Junction, [Your Company's
              Full Address Details Here, e.g., 123 Toy Street, Fun City, FC
              12345, Country].
            </li>
            <li>
              <strong>Cookies</strong> are small files that are placed on Your
              computer, mobile device or any other device by a website,
              containing the details of Your browsing history on that website
              among its many uses.
            </li>
            <li>
              <strong>Country</strong> refers to: [Your Country, e.g., United
              States].
            </li>
            <li>
              <strong>Device</strong> means any device that can access the
              Service such as a computer, a cellphone or a digital tablet.
            </li>
            <li>
              <strong>Personal Data</strong> is any information that relates to
              an identified or identifiable individual.
            </li>
            <li>
              <strong>Service</strong> refers to the Website.
            </li>
            <li>
              <strong>Service Provider</strong> means any natural or legal
              person who processes the data on behalf of the Company. It refers
              to third-party companies or individuals employed by the Company to
              facilitate the Service, to provide the Service on behalf of the
              Company, to perform services related to the Service or to assist
              the Company in analyzing how the Service is used.
            </li>
            <li>
              <strong>Usage Data</strong> refers to data collected
              automatically, either generated by the use of the Service or from
              the Service infrastructure itself (for example, the duration of a
              page visit).
            </li>
            <li>
              <strong>Website</strong> refers to The Joy Junction, accessible
              from https://thejoyjunction.com
            </li>
            <li>
              <strong>You</strong> means the individual accessing or using the
              Service, or the company, or other legal entity on behalf of which
              such individual is accessing or using the Service, as applicable.
            </li>
          </ul>

          <h2>2. Information We Collect</h2>
          <p>
            We collect personal information that you voluntarily provide to us
            when you register on the Services, express an interest in obtaining
            information about us or our products and services, when you
            participate in activities on the Services or otherwise when you
            contact us.
          </p>
          <p>
            The personal information that we collect depends on the context of
            your interactions with us and the Services, the choices you make and
            the products and features you use. The personal information we
            collect may include the following:
          </p>
          <ul>
            <li>
              <strong>Personal Information You Provide:</strong> Name, email
              address, phone number, mailing address, payment information, and
              other similar data.
            </li>
            <li>
              <strong>Information Collected Automatically:</strong> When you
              navigate our Services, we may also collect certain information
              automatically from your device. This information may include your
              IP address, browser type, operating system, referring URLs, device
              information, pages viewed, and dates/times of access.
            </li>
            <li>
              <strong>Information from Third Parties:</strong> We may receive
              information about you from other sources, such as public
              databases, joint marketing partners, social media platforms, as
              well as from other third parties.
            </li>
          </ul>

          <h2>3. How We Use Your Information</h2>
          <p>
            We use personal information collected via our Services for a variety
            of business purposes described below. We process your personal
            information for these purposes in reliance on our legitimate
            business interests, in order to enter into or perform a contract
            with you, with your consent, and/or for compliance with our legal
            obligations. We indicate the specific processing grounds we rely on
            next to each purpose listed below.
          </p>
          <ul>
            <li>To facilitate account creation and logon process.</li>
            <li>To send administrative information to you.</li>
            <li>To fulfill and manage your orders.</li>
            <li>To post testimonials (with your consent).</li>
            <li>To deliver targeted advertising to you.</li>
            <li>To request feedback.</li>
            <li>To protect our Services.</li>
            <li>To enforce our terms, conditions and policies.</li>
            <li>To respond to legal requests and prevent harm.</li>
            <li>
              For other business purposes, such as data analysis, identifying
              usage trends, determining the effectiveness of our promotional
              campaigns and to evaluate and improve our Services, products,
              marketing and your experience.
            </li>
          </ul>

          <h2>4. How We Share Your Information</h2>
          <p>
            We may process or share your data that we hold based on the
            following legal basis:
          </p>
          <ul>
            <li>
              <strong>With Service Providers:</strong> We may share your
              information with third-party vendors, service providers,
              contractors or agents who perform services for us or on our behalf
              and require access to such information to do that work.
            </li>
            <li>
              <strong>For Legal Reasons:</strong> We may disclose your
              information where we are legally required to do so in order to
              comply with applicable law, governmental requests, a judicial
              proceeding, court order, or legal process.
            </li>
            <li>
              <strong>Business Transfers:</strong> We may share or transfer your
              information in connection with, or during negotiations of, any
              merger, sale of company assets, financing, or acquisition of all
              or a portion of our business to another company.
            </li>
            <li>
              <strong>With Your Consent:</strong> We may disclose your personal
              information for any other purpose with your consent.
            </li>
          </ul>

          <h2>5. Your Choices and Rights</h2>
          <p>
            You have certain choices and rights regarding the personal
            information we collect and process about you.
          </p>
          <ul>
            <li>
              <strong>Access and Update Your Information:</strong> If you have
              an account with us, you may review and change your personal
              information by logging into your account and visiting your account
              profile page.
            </li>
            <li>
              <strong>Opt-Out of Marketing Communications:</strong> You can
              unsubscribe from our marketing email list at any time by clicking
              on the unsubscribe link in the emails that we send or by
              contacting us.
            </li>
            <li>
              <strong>Cookies and Tracking Technologies:</strong> Most Web
              browsers are set to accept cookies by default. If you prefer, you
              can usually choose to set your browser to remove cookies and to
              reject cookies.
            </li>
            <li>
              <strong>Do Not Track:</strong> Some Internet browsers offer a “Do
              Not Track” (“DNT”) signal. Because there is no common
              understanding of how to interpret DNT signals, our Services do not
              currently respond to DNT browser signals or mechanisms.
            </li>
          </ul>

          <h2>6. Data Security</h2>
          <p>
            We have implemented appropriate technical and organizational
            security measures designed to protect the security of any personal
            information we process. However, despite our safeguards and efforts
            to secure your information, no electronic transmission over the
            Internet or information storage technology can be guaranteed to be
            100% secure, so we cannot promise or guarantee that hackers,
            cybercriminals, or other unauthorized third parties will not be able
            to defeat our security, and improperly collect, access, steal, or
            modify your information.
          </p>

          <h2>7. Data Retention</h2>
          <p>
            We will only keep your personal information for as long as it is
            necessary for the purposes set out in this privacy policy, unless a
            longer retention period is required or permitted by law (such as
            tax, accounting or other legal requirements).
          </p>

          <h2>8. Children’s Privacy</h2>
          <p>
            Our Services are not directed to individuals under the age of 13 (or
            other age as required by local law), and we do not knowingly collect
            personal information from children. If we become aware that we have
            inadvertently collected personal information from a child, we will
            take reasonable steps to delete such information.
          </p>

          <h2>9. International Data Transfers</h2>
          <p>
            Your information, including personal information, may be transferred
            to — and maintained on — computers located outside of your state,
            province, country or other governmental jurisdiction where the data
            protection laws may differ from those from your jurisdiction. If you
            are located outside the United States and choose to provide
            information to us, please note that we transfer the data, including
            personal information, to the United States and process it there.
          </p>

          <h2>10. Changes to This Privacy Policy</h2>
          <p>
            We may update this privacy policy from time to time. The updated
            version will be indicated by an updated &quot;Last Updated&quot;
            date and the updated version will be effective as soon as it is
            accessible. We encourage you to review this privacy policy
            frequently to be informed of how we are protecting your information.
          </p>

          <h2>11. Contact Us</h2>
          <p>
            If you have questions or comments about this policy, you may email
            us at [Your Contact Email Address] or by post to:
          </p>
          <p>
            [Your Company Name]
            <br />
            [Your Company Address Line 1]
            <br />
            [Your Company Address Line 2, if any]
            <br />
            [City, State, Zip Code]
            <br />
            [Country]
          </p>
        </article>
      </div>
    </div>
  );
}
